apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx
  namespace: obligatorio
data:
  API_BASE_URL: "https://tpgod3irl3.execute-api.us-east-1.amazonaws.com"
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events { worker_connections 1024; }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log   /var/log/nginx/access.log  main;

      sendfile        on;
      keepalive_timeout  65;

      upstream backend { server users-api-service:8000; }
      upstream notify  { server notification-service:8081; }

      server {
        listen 3000;
        server_name app.joaquingonzalezutec.abrdns.com;

        return 301 https://$host$request_uri;
      }

      # Servidor HTTPS real
      server {
        listen 3443 ssl;
        server_name app.joaquingonzalezutec.abrdns.com;

        ssl_certificate     /etc/nginx/tls/tls.crt;
        ssl_certificate_key /etc/nginx/tls/tls.key;

        root /usr/share/nginx/html;
        index index.html;

        location /api/ {
          proxy_pass http://backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

        location /notify/ {
          proxy_pass http://notify/;
        }

        location / {
          try_files $uri /index.html;
        }
      }
    }